In [4]:
x=[1,2,3,4,5]
y=[7,14,15,18,19]

In [5]:
x=[1,2,3,4,5]
y=[7,14,15,18,19]

from sklearn.linear_model import LinearRegression
model=LinearRegression()
import numpy as np
x=np.array(x).reshape(-1,1)
y=np.array(y)
model.fit(x,y)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](1,)",[2.8]
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.",float64,6.2
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,1
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(1)
"singular_ singular_: array of shape (min(X, y),)Singular values of `X`. Only available when `X` is dense.","ndarray[float64](1,)",[3.16]


In [6]:
import pandas as pd

data=pd.read_csv('bp.csv')
data.head()

,Subject_ID,Age (years),Weight (kg),Systolic BP (mm Hg)
0,1,60,58,117
1,2,61,90,120
2,3,74,96,145
3,4,57,72,129
4,5,63,62,132


In [7]:
print(data.columns.tolist())

['Subject_ID', 'Age (years)', 'Weight (kg)', 'Systolic BP (mm Hg)']


In [8]:
print(x.shape,y.shape)

(5, 1) (5,)


In [9]:
import pandas as pd
data = pd.read_csv('bp.csv')
data.head()
y = data['Systolic BP (mm Hg)']
x = data.drop(['Systolic BP (mm Hg)','Subject_ID'], axis=1)
print(x.shape, y.shape)
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


(16, 2) (16,)


In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
model = LinearRegression()
model.fit(x_train,y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](2,)","[0.77,0.43]"
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Defined only when `X`has feature names that are all strings... versionadded:: 1.0","ndarray[object](2,)","['Age (years)','Weight (kg)']"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.",float64,44.35
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,2
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(2)


In [12]:
import pandas as pd

# Load the dataset
data = pd.read_csv("bp.csv")

# Display the first 5 rows
print(data.head())

# Define target (y)
y = data["Systolic BP (mm Hg)"]

# Define features (x)
x = data.drop(columns=["Systolic BP (mm Hg)", "Subject_ID"])

# Check shapes
print("X shape:", x.shape)
print("Y shape:", y.shape)

# Split into training and testing sets
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

print("Training set:", x_train.shape)
print("Testing set:", x_test.shape)

   Subject_ID  Age (years)  Weight (kg)  Systolic BP (mm Hg)
0           1           60           58                  117
1           2           61           90                  120
2           3           74           96                  145
3           4           57           72                  129
4           5           63           62                  132
X shape: (16, 2)
Y shape: (16,)
Training set: (12, 2)
Testing set: (4, 2)


In [13]:
age=int(input("Enter the age of the patient: "))
weight=int(input("Enter the weight of the patient: "))
bp_=model.predict([[age,weight]])
print("Predicted Systolic BP (mm Hg):", bp_[0])

Predicted Systolic BP (mm Hg): 104.65172680504014


c:\Users\user\OneDrive\Desktop\srm kt\srm\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [14]:
y = data['Systolic BP (mm Hg)']

x = data.drop(['Systolic BP (mm Hg)', 'Subject_ID'], axis=1)

In [15]:
from sklearn.metrics import mean_squared_error
error = mean_squared_error(y_test, model.predict(x_test))

In [16]:
print(error)

91.8582299717074


In [17]:
import pandas as pd

# 1. Load the brand new house rent dataset
house_data = pd.read_csv('House.Rent_Dataset.csv')

# 2. Print out the exact column names so we don't guess them
print("Exact Columns:", house_data.columns.tolist())

# 3. View the first 5 rows to see what the data looks like
house_data.head()

FileNotFoundError: [Errno 2] No such file or directory: 'House.Rent_Dataset.csv'

In [ ]:
y=house_data['Rent']
x=house_data.drop(['Rent','Posted On' ,'Floor','Area Locality'],axis=1)

In [ ]:
import category_encoders as ce
encoder = ce.LeaveOneOutEncoder(return_df=True)
x=encoder.fit_transform(x,y)

In [ ]:
print(x)

      BHK  Size     Area Type          City  Furnishing Status  \
0       2  1100  18676.943967  11648.319312       22468.505513   
1       2   800  18672.853988  11629.198853       38727.130222   
2       2  1000  18674.080982  11634.934990       38728.463556   
3       2   800  18676.943967  11648.319312       22468.505513   
4       2   850  52405.438398  11653.099426       22469.883682   
...   ...   ...           ...           ...                ...   
4741    2  1000  52402.173269  20561.455594       38729.352444   
4742    3  2000  18669.173006  20545.307958       38723.130222   
4743    3  1750  52393.466260  20538.387543       38720.463556   
4744    3  1500  52389.112756  20526.853518       38716.019111   
4745    2  1000  52402.173269  20561.455594       22465.749173   

      Tenant Preferred  Bathroom  Point of Contact  
0         31216.953238         2      16706.291757  
1         31214.048795         1      16703.181337  
2         31214.920128         1      16704.1144

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x=scaler.fit_transform(x)

In [ ]:
print(x)

[[0.2        0.13642053 0.27316184 ... 0.01795978 0.11111111 0.00321938]
 [0.2        0.09887359 0.27307371 ... 0.01780886 0.         0.00316481]
 [0.2        0.12390488 0.27310014 ... 0.01785413 0.         0.00318118]
 ...
 [0.4        0.21777222 0.99968293 ... 0.01758247 0.22222222 0.99965557]
 [0.4        0.1864831  0.99958912 ... 0.99558704 0.11111111 0.99954076]
 [0.2        0.12390488 0.99987054 ... 0.58744851 0.11111111 0.00319209]]


In [ ]:
import pandas as pd
x= pd.DataFrame(x)


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(x_train, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](8,)","[ 27628.24,276011.57, 8437.05,...,-10690.88, 82123.72, 11929.03]"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.",float64,-4.097e+04
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,8
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(8)
"singular_ singular_: array of shape (min(X, y),)Singular values of `X`. Only available when `X` is dense.","ndarray[float64](8,)","[36.15,21.12,19.56,...,11.19, 3.55, 2.52]"


In [ ]:
model.predict(x_train[1:2])

array([16756.99654701])

In [ ]:
new_house = pd.DataFrame({
    'BHK': [2],
    'Size': [1200],
    'Area Type': ['Super Area'],
    'City': ['Delhi'],
    'Furnishing Status': ['Semi-Furnished'],
    'Tenant Preferred': ['Family'],
    'Bathroom': [2],
    'Point of Contact': ['Contact Owner']
})

new_encoded = encoder.transform(new_house)
new_scaled = scaler.transform(new_encoded)
prediction = model.predict(new_scaled)

print("Predicted Rent:", prediction[0])

Predicted Rent: 23822.757353939065


In [ ]:
import joblib
artifacts ={
  "encoder": encoder,
  "scaler": scaler,
  "model": model
}

joblib.dump(artifacts, "house_rent_prediction.pkl")


['house_rent_prediction.pkl']

In [ ]:
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error
import category_encoders as ce
import joblib

In [ ]:
import pandas as pd 
from sklearn.pipeline import Pipeline 
from sklearn.linear_model import LinearRegression 
from sklearn.preprocessing import MinMaxScaler 
from sklearn.model_selection import train_test_split 
from sklearn.metrics import r2_score, mean_absolute_error 
import category_encoders as ce
import joblib

In [ ]:
pip install category_encoders

   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.5 MB 4.1 MB/s eta 0:00:03
   ---------------- ----------------------- 3.9/9.5 MB 9.5 MB/s eta 0:00:01
   ----------------------------- ---------- 7.1/9.5 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 11.7 MB/s  0:00:00

   ---------------------------------------- 0/3 [patsy]
   ---------------------------------------- 0/3 [patsy]
   ---------------------------------------- 0/3 [patsy]
   ---------------------------------------- 0/3 [patsy]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- --------------


[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
print(data.columns)

Index(['Subject_ID', 'Age (years)', 'Weight (kg)', 'Systolic BP (mm Hg)'], dtype='str')


In [ ]:
pip install pandas


  Using cached pandas-3.0.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached pandas-3.0.3-cp313-cp313-win_amd64.whl (9.8 MB)
Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
 


[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
pip install scikit-learn

  Using cached scikit_learn-1.9.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
  Using cached numpy-2.5.0-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
  Using cached scipy-1.18.0-cp313-cp313-win_amd64.whl.metadata (61 kB)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
  Using cached narwhals-2.23.0-py3-none-any.whl.metadata (15 kB)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.9.0-cp313-cp313-win_amd64.whl (8.2 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached narwhals-2.23.0-py3-none-any.whl (458 kB)
Using cached numpy-2.5.0-cp313-cp313-win_amd64.whl (12.4 MB)
Using cached scipy-1.18.0-cp313-cp313-win_amd64.whl (36.6 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)

   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   -


[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import pandas as pd
import joblib
import category_encoders as ce
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

# 1. Load Dataset
data = pd.read_csv("House_Rent_Dataset.csv")

# 2. Separate Features and Target
X = data.drop(columns=["Rent", "Posted On", "Floor", "Area Locality"])
y = data["Rent"]

# 3. Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# 4. Build the Pipeline (This glues everything together!)
pipeline = Pipeline([
    ("encoder", ce.LeaveOneOutEncoder()),
    ("scaler", MinMaxScaler()),
    ("model", LinearRegression())
])

# 5. Train the entire Pipeline at once
pipeline.fit(X_train, y_train)

# 6. Save the entire Pipeline into a single .pkl file
joblib.dump(pipeline, "house_rent_pipeline.pkl")
print("Pipeline saved successfully as house_rent_pipeline.pkl!")

Pipeline saved successfully as house_rent_pipeline.pkl!


In [ ]:
import pandas as pd
data = pd.read_csv("wine.csv")
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5


In [ ]:
import pandas as pd
data = pd.read_csv("wine.csv")
y=data['quality']
x=data.drop(['quality'],axis=1)

In [ ]:
import pandas as pd
data = pd.read_csv("wine.csv")
y=data['quality']
x=data.drop(['quality'],axis=1)
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)
model.predict(x_test[50:51])

c:\Users\user\OneDrive\Desktop\srm kt\myenv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([5])

In [ ]:
import pandas as pd
data=pd.read_csv('wine.csv')
y=data['quality']
x=data.drop(['quality'],axis=1)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(random_state=42)
model.fit(x_train,y_train)
from sklearn.metrics import accuracy_score
y_pred=model.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy of the model is: ",accuracy)

Accuracy of the model is:  0.67


In [ ]:
li = [1, 40, 6, 10, 45, 89, 100, 156]
cc1 = 7
cc2 = 48

clust1 =[]
clust2 =[]

for i in li:
    if abs(i-cc1) < abs(i-cc2):
        clust1.append(i)
    else:
        clust2.append(i)

print(clust1 ,clust2)

[1, 6, 10] [40, 45, 89, 100, 156]


In [ ]:
cc1=sum(clust1)/len(clust1)
cc2=sum(clust2)/len(clust2)
clust1=[]
clust2=[]
for i in li:
    if abs(i-cc1)<abs(i-cc2):
        clust1.append(i)
    else:
        clust2.append(i)
print(clust1,clust2)

[1, 40, 6, 10, 45] [89, 100, 156]


In [ ]:
cc1=sum(clust1)/len(clust1)
cc2=sum(clust2)/len(clust2)

clust1=[]
clust2=[]

for i in li:
    if abs(i-cc1)<abs(i-cc2):
        clust1.append(i)
    else:
        clust2.append(i)
print(clust1,clust2)  

[1, 40, 6, 10, 45] [89, 100, 156]


In [ ]:
li = [1, 40, 6, 10, 45, 89, 100, 156]
from sklearn.cluster import KMeans
import numpy as np
kmeans = KMeans(2)
model = kmeans.fit(np.array(li).reshape(-1,1))

In [ ]:
print(model.predict(np.array([[50]])))

[0]


In [ ]:
import tensorflow as tf
print(tf.__version__)

2.21.0


In [ ]:
import pandas as pd
data = pd.read_csv("wine.csv")
y = data['quality']
x = data.drop('quality', axis=1)
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25, random_state=42)

In [ ]:
from sklearn.neural_network import MLPClassifier
model = MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=500)
model.fit(x_train,y_train)

print(model.score(x_test,y_test))

0.5475


In [ ]:
from sklearn.metrics import confusion_matrix,classification_report
y_pred=model.predict(x_test)
confusion_matrix=confusion_matrix(y_test,y_pred)
print(confusion_matrix)

[[  0   0   1   0   0   0]
 [  0   0   9   4   0   0]
 [  0   0 127  35   2   0]
 [  0   0  77  86   6   0]
 [  0   0   8  34   6   0]
 [  0   0   0   3   2   0]]


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model=Sequential()
model.add(Dense(64,input_dim=x_train.shape[1],activation='relu'))
model.add(Dense(6,activation='softmax'))
model.summary()

c:\Users\user\OneDrive\Desktop\srm kt\srm\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           768 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 6)              │           390 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,158 (4.52 KB)

 Trainable params: 1,158 (4.52 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.predict(x_test)

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step  


array([[8.24101456e-03, 2.28749574e-04, 3.96931529e-01, 5.80881655e-01,
        5.27007796e-06, 1.37117757e-02],
       [1.07382766e-04, 3.71930220e-08, 7.16260791e-01, 2.77092695e-01,
        8.24145960e-11, 6.53905934e-03],
       [7.52774766e-03, 8.09797493e-04, 3.70690167e-01, 6.15605116e-01,
        6.56884877e-05, 5.30146016e-03],
       ...,
       [2.19179839e-02, 1.15664606e-03, 4.00637180e-01, 5.68486214e-01,
        5.38732056e-05, 7.74809951e-03],
       [3.25881243e-02, 5.43848705e-03, 5.65511882e-01, 3.57462585e-01,
        8.23506911e-04, 3.81753817e-02],
       [1.35017876e-02, 2.16079922e-03, 5.90690553e-01, 3.65500778e-01,
        3.46105546e-04, 2.77999230e-02]], shape=(400, 6), dtype=float32)

In [32]:
import numpy as np

# model.predict se jo decimals aaye hain, unmein se sabse badi value ka index nikalna
clean_predictions = np.argmax(model.predict(x_test), axis=1)

# Pehle 10 predictions dekhna ekdum saaf numbers mein
print("Wine ki predicted qualitieimports:")
print(clean_predictions[:10])

AxisError: axis 1 is out of bounds for array of dimension 1

In [33]:
pred = model.predict(x_test)
print(pred.shape)
print(pred[:5])

(4,)
[115.11990803 129.59759998 130.24041877 130.51587286]
